apiVersion: v1
kind: Pod
metadata:
  name: mysql-db
spec:
   containers:
    - name: my-db
      image: mysql:5.7
      env:
        - 
         name: MYSQL_ROOT_PASSWORD
         value: training
        - 
         name: MYSQL_DATABASE
         value: user-service
        - 
         name: MYSQL_USER
         value: docker
        - 
         name: MYSQL_PASSWORD
         value: training
