apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-dep
  labels:
    app: product-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service-app
  template:
    metadata:
      labels:
        app: product-service-app
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: product-service
        image: snehalsynerzip/product-service:1.0
        ports:
        - containerPort: 9001
