apiVersion: v1
kind: Pod
metadata:
  name: review-service-multi-pod
spec:
  hostNetwork: true
  containers:
  - name: review-service-multi-pod
    image: snehalsynerzip/review-service:multi-pod2
    ports:
    - containerPort: 9002
  - name: my-db
    image: mysql:5.7
    env:
    - 
     name: MYSQL_ROOT_PASSWORD
     value: training
    - 
     name: MYSQL_DATABASE
     value: review-service
    - 
     name: MYSQL_USER
     value: docker
    - 
     name: MYSQL_PASSWORD
     value: training


