apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-dep
  labels:
    app: product-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service-app
  template:
    metadata:
      labels:
        app: product-service-app
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: product-service
        image: syndemo/product-service:latest
        ports:
        - containerPort: 9001
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.25"
