apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service-dep
  labels:
    app: review-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-service-app
  template:
    metadata:
      labels:
        app: review-service-app
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name:  review-service
        image: syndemo/review-service:latest
        ports:
        - containerPort: 9002
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.25"
