apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: product-service-app
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30001
