spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform : org.hibernate.dialect.MySQL5Dialect
    show-sql : true
    generate-ddl : true
    hibernate:
      ddl-auto : update
  datasource:
    url : jdbc:mysql://localhost:3306/product-service
    username : docker
    password : training
    driver-class-name : com.mysql.jdbc.Driver
    testOnBorrow : true
    validationQuery : SELECT 1

server:
   port: 9001
