apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-service-dep
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50