apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: review-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: review-service-dep
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50