apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service-dep
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50