apiVersion: v1
kind: Pod
metadata:
  name: product-service-multi-pod
spec:
  hostNetwork: true
  containers:
  - name: product-service-multi-pod
    image: snehalsynerzip/product-service:multi-pod
    ports:
    - containerPort: 9001
  - name: my-db
    image: mysql:5.7
    env:
    - 
     name: MYSQL_ROOT_PASSWORD
     value: training
    - 
     name: MYSQL_DATABASE
     value: product-service
    - 
     name: MYSQL_USER
     value: docker
    - 
     name: MYSQL_PASSWORD
     value: training

